# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#

GMAIL_USERNAME: ong.dkrab@gmail.com
GMAIL_PASSWORD: wongsapat25
ADMIN_NAME: First User
ADMIN_EMAIL: ongkrab@cbas.com
ADMIN_PASSWORD: changeme
ROLES: [admin, user, VIP]

PATH_PERL: /home/ongkrab/MyProjectCbas/Deverlopment/codePerl/ProjectMain.pl

KASET_USERNAME: bxxxxxxx
KASET_PASSWORD: xxxxxxx

SMTP_SERVER_HOST: nontri.ku.ac.th
SMTP_SERVER_PORT: 25
SERVER_HOST_NAME: http://158.108.30.200